name: Android

#on: [push]
on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - uses: actions/checkout@v2

    - name: Refresh Ubuntu-repo
      run: sudo apt update

    - name: Init Toolchain submodule
      working-directory: ${{runner.workspace}}/TeamTalk5
      run: git submodule update --init Library/TeamTalkLib/toolchain

    - name: Init Toolchain's submodules
      working-directory: ${{runner.workspace}}/TeamTalk5/Library/TeamTalkLib/toolchain/build
      run: |
        make prepare-github

    - name: Install Toolchain Dependencies
      working-directory: ${{runner.workspace}}/TeamTalk5/Library/TeamTalkLib/toolchain/build
      run: |
        sudo make depend-ubuntu18

    - name: Build Toolchain for Android 32-bit ARM
      working-directory: ${{runner.workspace}}/TeamTalk5/Library/TeamTalkLib/toolchain
      shell: bash
      run: |
        source toolchain.sh android armeabi-v7a
        cd build
        make android-armeabi-v7a

    - name: Install TeamTalk Library Dependencies
      working-directory: ${{runner.workspace}}/TeamTalk5
      run: sudo make -C Build depend-ubuntu18

    - name: Build TeamTalk Library and Apps
      working-directory: ${{runner.workspace}}/TeamTalk5/Build
      run: make CMAKE_EXTRA="-DWEBRTC=OFF" android-armeabi-v7a

    - name: Doxygen Documentation
      working-directory: ${{runner.workspace}}/TeamTalk5/Build
      run: make dox
