name: iOS

#on: [push]
on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init Toolchain submodule
      working-directory: ${{runner.workspace}}/TeamTalk5
      run: git submodule update --init Library/TeamTalkLib/toolchain

    - name: Init Toolchain's submodules
      working-directory: ${{runner.workspace}}/TeamTalk5/Library/TeamTalkLib/toolchain/build
      run: |
        make prepare-github

    - name: Install Toolchain Dependencies
      working-directory: ${{runner.workspace}}/TeamTalk5/Library/TeamTalkLib/toolchain/build
      run: |
        brew update
        make depend-mac

    - name: Build Toolchain for iOS ARMv7
      working-directory: ${{runner.workspace}}/TeamTalk5/Library/TeamTalkLib/toolchain
      shell: bash
      run: |
        source toolchain.sh ios armv7
        cd build
        make ios-armv7

    - name: Install TeamTalk Library Dependencies
      run: brew install openjdk ninja doxygen

    - name: Build TeamTalk Library and Apps
      working-directory: ${{runner.workspace}}/TeamTalk5/Build
      run: make CMAKE_EXTRA="-DWEBRTC=OFF -DCMAKE_OSX_ARCHITECTURES=armv7 -DCMAKE_OSX_SYSROOT=iphoneos" BUILDDIR=build-ios-armv7 ios-build

    - name: Doxygen Documentation
      working-directory: ${{runner.workspace}}/TeamTalk5/Build
      run: make dox
